#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Usage :
    fontforge -script svg_to_ttf.py
"""

import os
import fontforge

def svg_to_ttf(svg_dir, output_ttf, font_name="You Font", version="1.0"):
    font = fontforge.font()

    font.familyname = font_name
    font.fullname = f"{font_name} Regular"
    font.fontname = font_name.replace(" ", "")
    font.copyright = "Generated by chinese-hershey-font"
    font.version = version

    font.em = 1024
    font.ascent = 800
    font.descent = 224

    svg_files = [f for f in os.listdir(svg_dir) if f.endswith('.svg')]

    print(f"找到 {len(svg_files)} 个 SVG 文件")

    imported = 0
    for svg_file in svg_files:
        try:
            code_point = int(svg_file.replace('.svg', ''))

            glyph = font.createChar(code_point)

            svg_path = os.path.join(svg_dir, svg_file)
            glyph.importOutlines(svg_path)
            glyph.width = 1024

            imported += 1
            if imported % 100 == 0:
                print(f"已导入 {imported} 个字符...")

        except Exception as e:
            print(f"导入 {svg_file} 时出错: {e}")

    print(f"总共导入 {imported} 个字符")
    print(f"正在生成 {output_ttf}...")
    font.generate(output_ttf)
    print(f"完成! 字体已保存到 {output_ttf}")


def main():
    svg_to_ttf(
        svg_dir='svg_output',
        output_ttf='you.ttf',
        font_name='You Font',
        version='1.0'
    )


if __name__ == "__main__":
    main()
